# Generated by Django 2.2.5 on 2019-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_auto_20191116_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_ciudad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombreCiudad',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_ciudad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_comuna',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombreComuna',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='fila',
            name='id_fila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='id_notaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='id_tramite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='nroFila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notaria',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=50),
        ),
        migrations.AddField(
            model_name='notaria',
            name='id_comuna',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notaria',
            name='id_notaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notaria',
            name='nombre_notaria',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='notaria',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='id_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='nombreRegion',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_fila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramite',
            name='id_tramite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramite',
            name='nombreTramite',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ap_materno',
            field=models.CharField(default='Sin ap materno', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ap_paterno',
            field=models.CharField(default='Sin ap paterno', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='Sin contraseña', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='No hay correo', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='Sin rut', max_length=9),
        ),
    ]
